spring:
  application:
    name: ContactPoints
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:contactpoints
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /cm

