CREATE TABLE CONTACT_POINTS_PHONE(
  ID VARCHAR (255) NOT NULL PRIMARY KEY,
  CUSTOMER_ID VARCHAR(255) NOT NULL,
  CONTACT_NO_CODE VARCHAR (3) NOT NULL,
  CONTACT_NO INTEGER(10) NOT NULL,
  STATUS VARCHAR (50) NOT NULL,
  REASON VARCHAR (100),
  CREATION_TIME TIMESTAMP NOT NULL,
  LAST_UPDATED_TIME TIMESTAMP,
  USER_ID VARCHAR (20),
  USER_NOTES VARCHAR (2000),
  VERSION INTEGER NOT NULL,
  UNIQUE KEY UNIQUE_CONTACT (CUSTOMER_ID, CONTACT_NO)
);

CREATE INDEX CONTACT_POINTS_PHONE_CUSTOMER_ID_IDX ON CONTACT_POINTS_PHONE (CUSTOMER_ID);
CREATE INDEX CONTACT_POINTS_PHONE_CONTACT_NO_IDX ON CONTACT_POINTS_PHONE (CONTACT_NO_CODE);
CREATE INDEX CONTACT_POINTS_PHONE_STATUS_IDX ON CONTACT_POINTS_PHONE (STATUS);
